language: node_js
node_js:
  - lts/*
env:
  - NODE_ENV=test
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
cache: yarn
script:
  - yarn test
skip_cleanup: true
on:
  branch: master